// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSLRoJ-DXGVJPIm4QfDz_bV6c4ctz4Ldg',
    appId: '1:442107364432:web:036f3b3450a4383950fd55',
    messagingSenderId: '442107364432',
    projectId: 'hqsync-139e9',
    authDomain: 'hqsync-139e9.firebaseapp.com',
    storageBucket: 'hqsync-139e9.firebasestorage.app',
    measurementId: 'G-H4LXG2SBYT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKPEQvSQvqCn3LdQx8rXgR3qYR1qN_UBE',
    appId: '1:442107364432:android:010e71a975a028d650fd55',
    messagingSenderId: '442107364432',
    projectId: 'hqsync-139e9',
    storageBucket: 'hqsync-139e9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbwARL_nxZCH3KuYmonqYT-tRqllJSH_w',
    appId: '1:442107364432:ios:0da7f4fcce37da8d50fd55',
    messagingSenderId: '442107364432',
    projectId: 'hqsync-139e9',
    storageBucket: 'hqsync-139e9.firebasestorage.app',
    iosBundleId: 'com.example.hqsync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbwARL_nxZCH3KuYmonqYT-tRqllJSH_w',
    appId: '1:442107364432:ios:0da7f4fcce37da8d50fd55',
    messagingSenderId: '442107364432',
    projectId: 'hqsync-139e9',
    storageBucket: 'hqsync-139e9.firebasestorage.app',
    iosBundleId: 'com.example.hqsync',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSLRoJ-DXGVJPIm4QfDz_bV6c4ctz4Ldg',
    appId: '1:442107364432:web:350152540b2bbae150fd55',
    messagingSenderId: '442107364432',
    projectId: 'hqsync-139e9',
    authDomain: 'hqsync-139e9.firebaseapp.com',
    storageBucket: 'hqsync-139e9.firebasestorage.app',
    measurementId: 'G-GS215GBB46',
  );
}
